# Generated by Django 5.2.1 on 2025-06-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='filliere',
            field=models.CharField(blank=True, choices=[('Informatique', 'Informatique'), ('Finance', 'Finance'), ('Industruelle', 'Industruelle')], max_length=20),
        ),
    ]
