# Generated by Django 5.2.1 on 2025-06-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_utilisateur_filliere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('professeur', 'Professeur'), ('etudiant', 'Étudiant')], max_length=20),
        ),
    ]
