# Generated by Django 5.2.1 on 2025-06-26 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('message', 'Nouveau message'), ('grade', 'Nouvelle note'), ('assignment', 'Nouveau devoir'), ('assignment_due', 'Devoir à rendre'), ('course', 'Nouveau cours'), ('absence', 'Absence enregistrée'), ('system', 'Notification système')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='emploidutemps',
            name='unique_subject_schedule',
        ),
        migrations.AddField(
            model_name='notification',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='matiere_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.matiere'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.message'),
        ),
    ]
