# Generated by Django 5.2 on 2025-06-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='assignment_title',
        ),
    ]
