# Generated by Django 5.2 on 2025-06-21 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0002_remove_assignmentsubmission_assignment_title'),
        ('prof', '0002_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prof.assignment'),
        ),
    ]
