# Generated by Django 5.2.1 on 2025-06-23 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_utilisateur_filliere'),
        ('prof', '0002_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='type_note',
            field=models.CharField(choices=[('exam', 'Examen'), ('controle', 'Contrôle'), ('discipline', 'Discipline')], default='exam', max_length=10, verbose_name='Type de la note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inscription'),
        ),
    ]
